network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      optional: true
    wlan0:
      dhcp4: false
      addresses:
        - 10.69.69.1/24
  bridges:
    br0:
      dhcp4: true
      interfaces:
        - eth0
        - wlan0
